version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000 #gunicorn core.wsgi --workers 2 -b 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
      - 3000:3000 # for debugpy
    depends_on:
      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
volumes:
  postgres_data:
